spring: 
  profiles: 
    active: 
    - dev
    
---
spring: 
  profiles: dev   #开发环境
  application: 
    name: microservicecloud-config-jl-dev
    
---
spring: 
  profiles: dev   #测试环境
  application: 
    name: microservicecloud-config-jl-test