spring: 
  profiles: 
    active: 
    - dev
    
---
server: 
  port: 7001
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client
  
eureka: 
  instance: 
    hostname: eureka7001.com       #eureka服务器的实例名
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false           #false表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #（单机版）设置与Eureka Server交互的地址，查询服务和注册服务
      defaultZone: http://eureka7001.com:7001/eureka/
      
---
server: 
  port: 7001
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-eureka-client

eureka: 
  instance: 
    hostname: eureka7001.com       #eureka服务器的实例名
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false           #false表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #（单机版）设置与Eureka Server交互的地址，查询服务和注册服务
      defaultZone: http://eureka7001.com:7001/eureka/
      